### ISSUE TITLE
Dashboard Performance With Large Data Sources

### ISSUE THREAD

**Issue by disteSp** [expand/eXpand#111]
Hi,

I write this post in reference to http://www.expandframework.com/forum/8-discussion/5254-dashboard-performance-with-large-data-sources.html#11729 . 

Please can you inform me when a model rules to modify the query further and on design/runtime mode is done.

Thanks,

Davide

**Comment by apobekiaris** [comment]
at the moment this is not possible however we can create model rules that can modify the sql statement for the 2 modes (runtime,designtime)

**Comment by apobekiaris** [comment]
You can create a new RecordsCount rule to filter your dashboards from v18.1.3.2. I will post a link to a nightly installer so you can test soon.

![image](https://user-images.githubusercontent.com/131656/41580785-c3640e72-73a4-11e8-9711-1fec2f734627.png)

**Comment by apobekiaris** [comment]
please test against https://www.dropbox.com/s/5ijs6fkd61iip88/eXpandFramework-18.1.2.11.exe?dl=0. Do not mind the file name the build is complied against XAF 18.1.3 and sources are included in the installed in case you want to recompile yourself. Let me know how it works.

**Comment by vimarx** [comment]
I'm a GitHub beginner, so I don't know if am I posting it correctly
Thanks

this issue is related #114

**Comment by disteSp** [comment]
> please test against https://www.dropbox.com/s/5ijs6fkd61iip88/eXpandFramework-18.1.2.11.exe?dl=0. Do not mind the file name the build is complied against XAF 18.1.3 and sources are included in the installed in case you want to recompile yourself. Let me know how it works.

Thanks  apobekiaris , After updating eXpand framework I can see the new data sources rule, but after enabling it and updating all models, It seem to have no effect both in dashboard designer and data sources preview. 
![topreturnedrecord](https://user-images.githubusercontent.com/40351623/41651481-f179db2a-7480-11e8-92cc-f827506093bf.PNG)

I still see more than the 10 records I set in the new rule

**Comment by apobekiaris** [comment]
can you provide exact instructions on how this fails? Using the XtradashboardTester solution I followed the next steps with success.
1. I modified the model.designdiffs.xafml to look like
```xml
<?xml version="1.0" encoding="utf-8"?>
<Application>
  <DashboardModule>
    <DataSources>
      <DashboardRecordsCount Id="All datasources @ desingtime" DataSourceName=".*" RecordsCount="1" Enabled="DesignTime" IsNewNode="True" />
    </DataSources>
  </DashboardModule>
</Application>
```
2. I created a new Dashboard for the Customer object, edited the dashboard, add a Grid and noticed 2 1 records.
3. remove the model modifications and reopen the dashboard and the grid displays 2 records now.

**Comment by disteSp** [comment]
I create a new dashboard and the new filter is applied in designer. Instead if I edit an Existing dashboard created before the new filter I see all the record in designer. Is it the correct behavior?

**Comment by disteSp** [comment]
I have another question. Is it possible to use Use the DataView Mode suggested in the second part of the article within Xpand Dashboard Module?
In a similar way to this DevEx example:
`using DevExpress.ExpressApp.Dashboards;
// ... 
public class CustomDashboardDataProvider : DashboardDataProvider {
    protected override IObjectDataSourceCustomFillService CreateViewService(IDashboardData dashboardData) {
        if(dashboardData.Title == "Sales Overview") {
            return new DashboardViewDataSourceFillService();
        }
        return base.CreateViewService(dashboardData);
    }
}`

**Comment by apobekiaris** [comment]
> if I edit an Existing dashboard created before the new filter.

This makes no sense to me. What I have to do to repro the case please post very very detailed steps. 

about your second case no it is not supported feel free to open another ticket if you wish a future implementation.

**Comment by apobekiaris** [comment]
details like exact steps on how/when you create the dashboard? what type, and how/when you create the filter.

**Comment by disteSp** [comment]
1) I have an existing dashboard create with the previous version of Expand, attached here the relative xml.
2)I click on Edit dashboard.
3)Dashboard designer is opened.
4) In dashboard I have a table that shows all the records and not only the first 10 (the value in RecordsCo
[test.zip](https://github.com/expand/eXpand/files/2124519/test.zip)

unt rule).

**Comment by apobekiaris** [comment]
Your xml uses an SqlDataSource while this implementation works only an ObjectDataSource (Xaf BO objects).

**Comment by disteSp** [comment]
Ok thanks for the clarification.
