### ISSUE TITLE
17.2 releases.

### ISSUE THREAD

**Issue by qaqolp2** [expand/eXpand#116]
Hi,
I see latest 17.2 release of expand version is 17.2.7.4. 
Is expand 17.2.7.4 compatible with any XAF 17.2.X.X ? (I mean 17.2.8 and later)
Regards.
Qaqolp.

**Comment by apobekiaris** [comment]
no its only compatible with the 17.2.7, I guess 17.2.8 was released after 18.1.x and we do not publish for such cases. I suggest you download the sources in 17.2.7 run the 17.2.8 ProjectConverter and build the framework using the scripts on the root

**Comment by qaqolp2** [comment]
Thank you.
