### ISSUE TITLE
eXpand Framework Project wizard and toolbox not there

### ISSUE THREAD

**Issue by semo981** [expand/eXpand#118]
after installation, I can't add the module from toolbox because it's not there and the project wizard also

**Comment by apobekiaris** [comment]
any message during installation? what your system specs? did it worked before I mean if you already installed a previous version

**Comment by semo981** [comment]
I installed 17.2.7.4 using the following:
VS2017
Devexpress 17.2.8.0
this is my first installation, I didn't install any previous version

**Comment by semo981** [comment]
I did what you advise in #116 and I install Devexpress 17.2.7 with eXpand 17.2.7.4 but still the same problem.

**Comment by apobekiaris** [comment]
Can you try to execute Xpand.ToolboxCreator.exe from your Xpand.dll installation folder or download the seperate Xpand.VSIX file and run it.

**Comment by semo981** [comment]
it's working now, thank you for your support
