### ISSUE TITLE
Application Settings - Model

### ISSUE THREAD

**Issue by skybluex3** [expand/eXpand#119]
Hello Tolis
I cant open Any model 
I tried open ModelDifferenceObject_Listview records and i got errors

You can see with this way=> Open Xpand Win Application, GO MDO_ListView, double click any model

Parameter cannot be null
Parametre name: typesInfo

   konum: DevExpress.Utils.Guard.ThrowArgumentNullException(String propName)
   konum: Xpand.Persistent.Base.General.TypesInfoExtensions.AssignAsInstance(ITypesInfo typesInfo)
   konum: Xpand.Persistent.Base.ModelDifference.ModelBuilder.CreateModulesManager(XafApplication application, String configFileName, String assembliesPath, ITypesInfo typesInfo)
   konum: Xpand.Persistent.Base.ModelDifference.ModelBuilder.Build(Boolean rebuild)
   konum: Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModelCore(Boolean rebuild)
   konum: Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(XafApplication xafApplication, Action`1 action)
   konum: Xpand.Persistent.Base.ModelDifference.ModelLoader.<>c__DisplayClass12_0.<GetMasterModel>b__0()
   konum: Xpand.Utils.Helpers.Retry.<>c__DisplayClass0_0.<Do>b__0()
   konum: Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)

**Comment by skybluex3** [comment]
full log file :

https://file.io/LhWquD

**Comment by apobekiaris** [comment]
Hi,

I am afraid I cannot repro it, I tried both the ModelDifferenceTester solution and a new empty solution with the MDO module as generated from the New Project Wizard. Can you provide a sample or more details on how this happens?
