### ISSUE TITLE
Invalid cast exception in DashboardViewEditorWeb.DashboardViewer property reference

### ISSUE THREAD

**Issue by disteSp** [expand/eXpand#120]
I'm using dashboard module in my xaf web application.

If I try to access the property DashboardViewer of DashboardViewEditorWeb class I receive an invalid cast exception.

In source code I see that 
` public ASPxDashboardViewer DashboardViewer {
            get { return (ASPxDashboardViewer)Control; }
        }`

Is it correct?

Debugging, I see that the private variable ASPxDashboardViewer _asPxDashboardViewer;  is correctly populated. 
Could the property DashboardViewer be something similar to:
`public ASPxDashboardViewer DashboardViewer {
            get { return _asPxDashboardViewer; }
        }`
?

thanks,

Davide

**Comment by apobekiaris** [comment]
Yes you are right there is a problem there, I will fix it in the next minor. Do you need a patched installer?

**Comment by disteSp** [comment]
If you have the fix, please could you send me the compiled assembly?

thanks and regards,

Davide

**Comment by apobekiaris** [comment]
[Xpand.DLL.zip](https://github.com/expand/eXpand/files/2158811/Xpand.DLL.zip)

**Comment by disteSp** [comment]
Thanks,

Inside the zip I find XtraDashboardTester.Module.Web.dll, is it the correct one?

**Comment by apobekiaris** [comment]
sorry here the correct files
[Xpand.DLL.zip](https://github.com/expand/eXpand/files/2159503/Xpand.DLL.zip)

**Comment by disteSp** [comment]
Sorry, I'm still having the same issue also with the new DLL
![pictures](https://user-images.githubusercontent.com/40351623/42230849-49eb1a30-7eea-11e8-9fe4-76075a338599.png)

**Comment by apobekiaris** [comment]
I used DotPeek on the posted assembly and the change is there.
![image](https://user-images.githubusercontent.com/159464/42259371-d23f0f62-7f68-11e8-83a0-763c06a912f0.png)
You can also try the installer from https://www.dropbox.com/s/thzl3414yp432dt/eXpandFramework-18.1.4.2.exe?dl=0

**Comment by disteSp** [comment]
Yes, you are right... I had duplicate Xpand assemblies in GAC, I think because new dlls have a new version but the same publicToken. After deleting old version from GAC and restart iis the issue is no more present.

Thanks
