### ISSUE TITLE
Update latest download link

### ISSUE THREAD

**Issue by emartsoft** [expand/eXpand#122]
It'll be helpful if you can update the Latest Download link on expandframework.com to point to https://github.com/expand/eXpand/releases and not https://github.com/expand/eXpand/issues.

**Comment by apobekiaris** [comment]
the link you posted points to https://github.com/expand/eXpand/releases and not to issues, can you be more specific?

**Comment by emartsoft** [comment]
The redirect link in expandframework.com point to github issues page. I feel that it should be pointing to release page.

Attached screenshot highlights the issue:

![image](https://user-images.githubusercontent.com/8901546/42636912-66c4cfac-85d9-11e8-80f5-7713d05738ee.png)

**Comment by apobekiaris** [comment]
fixed
