### ISSUE TITLE
Error when run FeatureCenter.Web

### ISSUE THREAD

**Issue by garung10a** [expand/eXpand#126]
I can built and run FeatureCenter.Win, but when I switch to FeatureCenter.Web, I can built successfully but after i log in under user admin. The system throw an error: DevExpress.Xpo.Exceptions.PropertyMissingException: 'Property 'Customer' does not exist within type 'FeatureCenter.Module.WorldCreator.ExistentAssemblyMasterDetail.EAMDOrder

**Comment by apobekiaris** [comment]
try this [patch](https://www.dropbox.com/s/n7cabz533mitaqj/eXpandFramework-18.1.4.12.exe?dl=0) instead and let me know if problems please

**Comment by garung10a** [comment]
Everything is fine now. Tks @apobekiaris
