### ISSUE TITLE
Workflow Server - How to run

### ISSUE THREAD

**Issue by isatahiri** [expand/eXpand#127]
Hello,

I'm use the workflow of xaf and the module of Expand is really usefull as i need to trigger a WF based on property change. 

Initial situation : 
I have a pure xaf app in winform and asp. I have created a xaf workflow server. (everything is made base on xaf doc)

I added : XpandSystemModule,Xpand, SystemWindowsFormsModuleXpandWorkflowModule.
After this, i have to add in navigation menu, a menu point to "ObjectChangedWorkflow_ListView"

My first test :  I created a simple workflow form "ObjectChangedWorkflow_ListView".

In client mode : OK 
In server mode : KO

The WF service was uninstalled and installed again. 
Do i have to do something to make ? 

Many thanks in advance if you could give me some guideline on this. 

BR
ISA

**Comment by isatahiri** [comment]
One more detail : 
In standard XAF the server mode works. 

BR
ISA

**Comment by apobekiaris** [comment]
have you already looked at the [configuration done](https://github.com/expand/eXpand/blob/18.1/Demos/Modules/Workflow/WorkflowTester.Win/Program.cs) in the related WorkflowTester solution? There are also [a few EasyTests](https://github.com/expand/eXpand/tree/18.1/Demos/Modules/Workflow/WorkflowTester.Module/FunctionalTests) on the module

**Comment by isatahiri** [comment]
Hello,

Well this is not quite clear for me. In the Workflow tester solution, the Workflow starter is instantiated on the logon of the win application. But if I have a service on a defined server, i should not do it in this way normally. 

What i need is to instantiate it into the service (in the OnStart) so what i did is commenting the standard part of the workflow server and tried to instantiate it as the workflow tester solution : 
This does not work.  Can you help please ? 

--------------------------------------------------------
using System;
using System.Configuration;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.ServiceProcess;
using System.Text;
using System.ServiceModel;
using DevExpress.ExpressApp.Workflow.Server;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.Security;
using DevExpress.Data.Filtering;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp.Workflow;
using DevExpress.Workflow;
using DevExpress.ExpressApp.MiddleTier;
using KBA_ADDON.Win;
using KBA_ADDON.Module.Win;

namespace KBA_ADDON.WorkflowServerService {
    public partial class KBA_ADDONWorkflowServer  : System.ServiceProcess.ServiceBase {
        private WorkflowServer server;
    //    protected override void OnStart(string[] args) {
    //        if(server == null) {
    //            ServerApplication serverApplication = new ServerApplication();
    //            serverApplication.ApplicationName = "KBA_ADDON";
				//serverApplication.CheckCompatibilityType = CheckCompatibilityType.DatabaseSchema;
    //            // The service can only manage workflows for those business classes that are contained in Modules specified by the serverApplication.Modules collection.
    //            // So, do not forget to add the required Modules to this collection via the serverApplication.Modules.Add method.
    //            serverApplication.Modules.BeginInit();
    //            serverApplication.Modules.Add(new WorkflowModule());
    //            serverApplication.Modules.Add(new KBA_ADDON.Module.KBA_ADDONModule());
    //            serverApplication.Modules.Add(new KBA_ADDON.Module.Win.KBA_ADDONWindowsFormsModule());
    //            serverApplication.Modules.Add(new KBA_ADDON.Module.Web.KBA_ADDONAspNetModule());
    //            if(ConfigurationManager.ConnectionStrings["ConnectionString"] != null) {
    //                serverApplication.ConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
    //            }
    //            serverApplication.Setup();
    //            serverApplication.Logon();

    //            IObjectSpaceProvider objectSpaceProvider = serverApplication.ObjectSpaceProvider;

    //            WorkflowCreationKnownTypesProvider.AddKnownType(typeof(DevExpress.Xpo.Helpers.IdList));

    //            server = new WorkflowServer("http://localhost:46232", new BasicHttpBinding(), objectSpaceProvider, objectSpaceProvider);
    //            server.StartWorkflowListenerService.DelayPeriod = TimeSpan.FromSeconds(15);
    //            server.StartWorkflowByRequestService.DelayPeriod = TimeSpan.FromSeconds(15);
    //            server.RefreshWorkflowDefinitionsService.DelayPeriod = TimeSpan.FromMinutes(15);

    //            server.CustomizeHost += delegate(object sender, CustomizeHostEventArgs e) {
    //                e.WorkflowInstanceStoreBehavior.WorkflowInstanceStore.RunnableInstancesDetectionPeriod = TimeSpan.FromSeconds(15);
    //            };

    //            server.CustomHandleException += delegate(object sender, CustomHandleServiceExceptionEventArgs e) {
    //                Tracing.Tracer.LogError(e.Exception);
    //                e.Handled = false;
    //            };
    //        }
    //        server.Start();
    //    }
        protected override void OnStart(string[] args)
        {

            var winApplication = new KBA_ADDONWindowsFormsApplication();
            if (ConfigurationManager.ConnectionStrings["ConnectionString"] != null)
            {
                winApplication.ConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            }

            WorkflowServerStarter workflowServerStarter = null;
            workflowServerStarter = new WorkflowServerStarter();
            workflowServerStarter.Start<KBA_ADDONWindowsFormsModule>(winApplication);

        }

        protected override void OnStop() {
            server.Stop();
        }
        public KBA_ADDONWorkflowServer() {
            InitializeComponent();
        }
    }
}

**Comment by isatahiri** [comment]
Hello,

I went a bit deeper and i found out that i can use it in the same way as the sandard : 
------------------------------------------------------
private XpandWorkflowServer _xpandWorkflowServer;
        private void Start_(string connectionString, string applicationName)
        {
            var securityComplex = new SecurityComplex<User, Role>(new WorkflowServerAuthentication(new BinaryOperator("UserName", "WorkflowService")));
            var serverApplication = new XpandWorkflowApplication(securityComplex);
            serverApplication.Modules.Add(new WorkflowModule());
            serverApplication.Modules.Add(new KBA_ADDON.Module.KBA_ADDONModule());
            serverApplication.Modules.Add(new KBA_ADDON.Module.Win.KBA_ADDONWindowsFormsModule());
            serverApplication.Modules.Add(new KBA_ADDON.Module.Web.KBA_ADDONAspNetModule());
            serverApplication.ApplicationName = applicationName;
            serverApplication.ConnectionString = connectionString;

            serverApplication.Security = securityComplex;
            serverApplication.Setup();
            serverApplication.Logon();

            IObjectSpaceProvider objectSpaceProvider = serverApplication.ObjectSpaceProvider;
            //WorkflowCreationKnownTypesProvider.AddKnownType(typeof(DevExpress.Xpo.Helpers.IdList));

            List<Type> _list = new List<Type>();
            _list.Add(typeof(ScheduledWorkflow));
            _list.Add(typeof(ObjectChangedWorkflow));

            _xpandWorkflowServer.WorkflowDefinitionProvider = new XpandWorkflowDefinitionProvider(typeof(XpoWorkflowDefinition), _list);

            _xpandWorkflowServer.CustomizeHost += delegate (object sender, CustomizeHostEventArgs e) {
                //
                // SqlWorkflowInstanceStoreBehavior
                //
                //e.WorkflowInstanceStoreBehavior = null;
                //System.ServiceModel.Activities.Description.SqlWorkflowInstanceStoreBehavior sqlWorkflowInstanceStoreBehavior = new System.ServiceModel.Activities.Description.SqlWorkflowInstanceStoreBehavior("Integrated Security=SSPI;Pooling=false;Data Source=(local);Initial Catalog=WorkflowsStore");
                //sqlWorkflowInstanceStoreBehavior.RunnableInstancesDetectionPeriod = TimeSpan.FromSeconds(2);
                //e.Host.Description.Behaviors.Add(sqlWorkflowInstanceStoreBehavior);
                //e.WorkflowIdleBehavior.TimeToPersist = TimeSpan.FromSeconds(1);
                e.WorkflowInstanceStoreBehavior.WorkflowInstanceStore.RunnableInstancesDetectionPeriod = TimeSpan.FromSeconds(2);
            };
            //_xpandWorkflowServer.WorkflowDefinitionProvider = new XpandWorkflowDefinitionProvider(typeof(XpoWorkflowDefinition), new List<Type> { typeof(ScheduledWorkflow), typeof(ObjectChangedWorkflow) });
            _xpandWorkflowServer.StartWorkflowListenerService.DelayPeriod = TimeSpan.FromSeconds(5);
            _xpandWorkflowServer.StartWorkflowByRequestService.DelayPeriod = TimeSpan.FromSeconds(5);
            _xpandWorkflowServer.RefreshWorkflowDefinitionsService.DelayPeriod = TimeSpan.FromSeconds(60);

            _xpandWorkflowServer.CustomHandleException += delegate (object sender, CustomHandleServiceExceptionEventArgs e) {
                Tracing.Tracer.LogError(e.Exception);
                if (OnCustomHandleException_ != null)
                {
                    OnCustomHandleException_(this, new ExceptionEventArgs("Exception occurs:\r\n\r\n" + e.Exception.Message + "\r\n\r\n'" + e.Service.GetType() + "' service"));
                }
                e.Handled = true;
            };
            _xpandWorkflowServer.Start();
        }
------------------------------------------------------

But i'm blocked into this : 

List<Type> _list = new List<Type>();
            _list.Add(typeof(ScheduledWorkflow));
            _list.Add(typeof(ObjectChangedWorkflow));

            _xpandWorkflowServer.WorkflowDefinitionProvider = new XpandWorkflowDefinitionProvider(typeof(XpoWorkflowDefinition), _list);

Can you help please ? 

BR
ISA

**Comment by isatahiri** [comment]
Hello,

I went a bit deeper and i found out that i can use it in the same way as the sandard :

--------------
private XpandWorkflowServer xpandWorkflowServer;
private void Start(string connectionString, string applicationName)
{
var securityComplex = new SecurityComplex<User, Role>(new WorkflowServerAuthentication(new BinaryOperator("UserName", "WorkflowService")));
var serverApplication = new XpandWorkflowApplication(securityComplex);
serverApplication.Modules.Add(new WorkflowModule());
serverApplication.Modules.Add(new KBA_ADDON.Module.KBA_ADDONModule());
serverApplication.Modules.Add(new KBA_ADDON.Module.Win.KBA_ADDONWindowsFormsModule());
serverApplication.Modules.Add(new KBA_ADDON.Module.Web.KBA_ADDONAspNetModule());
serverApplication.ApplicationName = applicationName;
serverApplication.ConnectionString = connectionString;

        serverApplication.Security = securityComplex;
        serverApplication.Setup();
        serverApplication.Logon();

        IObjectSpaceProvider objectSpaceProvider = serverApplication.ObjectSpaceProvider;
        //WorkflowCreationKnownTypesProvider.AddKnownType(typeof(DevExpress.Xpo.Helpers.IdList));

        List<Type> _list = new List<Type>();
        _list.Add(typeof(ScheduledWorkflow));
        _list.Add(typeof(ObjectChangedWorkflow));

        _xpandWorkflowServer.WorkflowDefinitionProvider = new XpandWorkflowDefinitionProvider(typeof(XpoWorkflowDefinition), _list);

        _xpandWorkflowServer.CustomizeHost += delegate (object sender, CustomizeHostEventArgs e) {
            //
            // SqlWorkflowInstanceStoreBehavior
            //
            //e.WorkflowInstanceStoreBehavior = null;
            //System.ServiceModel.Activities.Description.SqlWorkflowInstanceStoreBehavior sqlWorkflowInstanceStoreBehavior = new System.ServiceModel.Activities.Description.SqlWorkflowInstanceStoreBehavior("Integrated Security=SSPI;Pooling=false;Data Source=(local);Initial Catalog=WorkflowsStore");
            //sqlWorkflowInstanceStoreBehavior.RunnableInstancesDetectionPeriod = TimeSpan.FromSeconds(2);
            //e.Host.Description.Behaviors.Add(sqlWorkflowInstanceStoreBehavior);
            //e.WorkflowIdleBehavior.TimeToPersist = TimeSpan.FromSeconds(1);
            e.WorkflowInstanceStoreBehavior.WorkflowInstanceStore.RunnableInstancesDetectionPeriod = TimeSpan.FromSeconds(2);
        };
        //_xpandWorkflowServer.WorkflowDefinitionProvider = new XpandWorkflowDefinitionProvider(typeof(XpoWorkflowDefinition), new List<Type> { typeof(ScheduledWorkflow), typeof(ObjectChangedWorkflow) });
        _xpandWorkflowServer.StartWorkflowListenerService.DelayPeriod = TimeSpan.FromSeconds(5);
        _xpandWorkflowServer.StartWorkflowByRequestService.DelayPeriod = TimeSpan.FromSeconds(5);
        _xpandWorkflowServer.RefreshWorkflowDefinitionsService.DelayPeriod = TimeSpan.FromSeconds(60);

        _xpandWorkflowServer.CustomHandleException += delegate (object sender, CustomHandleServiceExceptionEventArgs e) {
            Tracing.Tracer.LogError(e.Exception);
            if (OnCustomHandleException_ != null)
            {
                OnCustomHandleException_(this, new ExceptionEventArgs("Exception occurs:\r\n\r\n" + e.Exception.Message + "\r\n\r\n'" + e.Service.GetType() + "' service"));
            }
            e.Handled = true;
        };
        _xpandWorkflowServer.Start();
    }
	
---------------
But i'm blocked into this :

List _list = new List();
_list.Add(typeof(ScheduledWorkflow));
_list.Add(typeof(ObjectChangedWorkflow));

_xpandWorkflowServer.WorkflowDefinitionProvider = new XpandWorkflowDefinitionProvider(typeof(XpoWorkflowDefinition), _list);

Can you help me please. 

BR
ISA

**Comment by isatahiri** [comment]
I changed the line by : 
 List<Type> _list = new List<Type>();
            _list.Add(typeof(ScheduledWorkflow));
            _list.Add(typeof(ObjectChangedWorkflow));

            _xpandWorkflowServer.WorkflowDefinitionProvider = new XpandWorkflowDefinitionProvider<XpoUserActivityVersion>(_list);

But my workflows are not running in server mode. 
Something must be wrong. 

Can you help please ? 

Many thanks 
Tahiri Isa

**Comment by apobekiaris** [comment]
>This does not work. Can you help please ?

provide details on what does not work I cannot read or test code you post without directions I am not magician. The Tester solution does what you need. The server although its created in the same Program.cs it uses a different application domain, the main app and the server communicate through WCF.

https://github.com/expand/eXpand/blob/18.1/Demos/Modules/Workflow/WorkflowTester.Win/Program.cs#L46

check out the https://github.com/expand/eXpand/blob/55460f2cb8cb8d5ccf106fdb46278cd1c62f1ce6/Xpand/Xpand.ExpressApp.Modules/Workflow/WorkflowServerStarter.cs#L41-L77 to see how is done

**Comment by isatahiri** [comment]
Hello,

Indeed, i used the WorkflowServerStarter in the service directly. 
Sorry the the messy code. 

 protected override void OnStart(string[] args)
        {
            var winApplication = new Win.KBA_ADDONWindowsFormsApplication();
            if (ConfigurationManager.ConnectionStrings["ConnectionString"] != null)
            {
                winApplication.ConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            }

            workflowServerStarter = new WorkflowServerStarter();
            workflowServerStarter.Start<KBA_ADDONWindowsFormsModule>(winApplication);
        }
BR
ISA
