### ISSUE TITLE
Workflow module support multi properties in ObjectChangeWorkflow

### ISSUE THREAD

**Issue by isatahiri** [expand/eXpand#128]
Hello,

I want to use the workflow module in order to monitor some property changes.

In the Xpand module, we can only choose one property. Would that be possible to choose a list of properties in the same WF ? I done not want to create one WF per property.

If yes could you give me some guide line of the potential adaptation to do ? 

Many thanks for your answer. 

BR
ISA

**Comment by apobekiaris** [comment]
in this [patch](https://www.dropbox.com/s/0cknhmqd5csf6w8/eXpandFramework-18.1.4.16.exe?dl=0) you can use a Regex to match the propertyname

**Comment by apobekiaris** [comment]
4db4e62f0c7ab9d15d11d25e3f281f1254bf74ab

**Comment by isatahiri** [comment]
Hello,

Thank you for the patch. I created a simple WF base on two properties with regex. (see attachment) but the the WF is running multiple times. 
Can you pleace check it is a error in the framework somehow ? Maybe the regex interpretation ? 
The WF is quite simple and I do not see any issue in my side. 

[WF On Property Change.pdf](https://github.com/expand/eXpand/files/2257868/WF.On.Property.Change.pdf)

Many thanks

Best regards,
Tahiri Isa

**Comment by apobekiaris** [comment]
please provide a sample project and db

**Comment by isatahiri** [comment]
Hello,

I created a sample project. It reacts exactly in the same way. 

Thank you for your help.

BR
ISA

[Xaf_Test_ExpandWF.zip](https://github.com/expand/eXpand/files/2265627/Xaf_Test_ExpandWF.zip)
[DB.zip](https://github.com/expand/eXpand/files/2265629/DB.zip)

**Comment by isatahiri** [comment]
Hello,

It works ! Thank you very much. 

BR
ISA
