### ISSUE TITLE
PermissionTransitionStateController not working in new middle tier implementation

### ISSUE THREAD

**Issue by krombipils** [expand/eXpand#129]
Hi,
I already mentioned this a while ago in the [old forum](http://www.expandframework.com/support/forum/6-bugs/5191-migrate-to-the-new-17-2-middle-tier-implementation.html), but unfortunately the problem is still not fixed:

The PermissionTransitionStateController (and other controllers too) does not work in the new middle tier implementation, because it uses the `IsAdministratorPermissionRequest`. You added a check in the `OnActivated` method: `if (Application.Security is ServerSecurityClient) return;`, but the new implementation does not use `ServerSecurityClient` but `MiddleTierClientSecurity`.

**Comment by apobekiaris** [comment]
yes you are right that call was only for .NET Remoting, this [patch](https://www.dropbox.com/s/ftuavfq5a4d1qau/eXpandFramework-18.1.5.12.exe?dl=0) includes both cases.

**Comment by krombipils** [comment]
Your patch fixed the problems. Thank you!
