### ISSUE TITLE
Issue with XpandLayoutManager

### ISSUE THREAD

**Issue by garung10a** [expand/eXpand#130]
I need to customize WebLayoutManager to avoid large gaps between the editor and its caption. I follow this link https://github.com/DevExpress-Examples/how-to-customize-weblayoutmanager-to-avoid-large-gaps-between-the-editor-and-its-caption-t228434/tree/17.1.3%2B/CS/WebLayoutSolution.Module.Web. I run project from this link, everything is fine, I can change gaps between the editor and its caption. But when I include WebLayoutManagerEx in this project into my project. The WebLayoutManagerEx has no effect, I cannot change the gaps. According to Devexpress document, to change LayoutManager, I need to override XafApplication.CreateLayoutManagerCore. In my application, I've already override that function and return WebLayoutManagerEx but I don't know why that have no effect. I've already debug my project and find out somehow the LayoutManager is XpandLayoutManager even without override CreateLayoutManagerCore. If I change WebLayoutManagerEx to inherit XpandLayoutManager instead WebLayoutManager, everything is fine, I can change the gaps. But I don't know is there any potential issue if i do it that way

**Comment by apobekiaris** [comment]
yes eXpandFramework changes the LayoutManager and sure you are safe to derive from XpandLayoutManager instead.

**Comment by apobekiaris** [comment]
I am sorry bad answer, I [patched](https://www.dropbox.com/s/oyzqnv6n18qj467/eXpandFramework-18.1.4.17.exe?dl=0) the source code to allow to override. For this you need to provide a class that implements the Xpand.Persistent.Base.General.ILayoutManager at least.

**Comment by apobekiaris** [comment]
no need to override any method the XafTypesInfo should be able to detect your custom provider.

at least it did on my side.

**Comment by garung10a** [comment]
> yes eXpandFramework changes the LayoutManager and sure you are safe to derive from XpandLayoutManager instead.
> 
 I've dug into the Xpand source code but I cant find the code that switch the LayoutManager to XpandLayoutManager 
> I am sorry bad answer, I patched the source code to allow to override. For this you need to provide a class that implements the Xpand.Persistent.Base.General.ILayoutManager at least.
 > 
So you mean inherit directly from XpandLayoutManager is not safe. Before your answer, I've already try to inherit XpandLayoutManager with unpatched Xpand . Everything is fine. I just afraid of potential issues

> no need to override any method the XafTypesInfo should be able to detect your custom provider.
at least it did on my side.
> 
Ok, I'll try this way

**Comment by garung10a** [comment]
> no need to override any method the XafTypesInfo should be able to detect your custom provider.
at least it did on my side.
> 
By the new way, WebLayoutManagerEx  inherit from WebLayoutManager (no need inherit from XpandLayoutManager) and ILayoutManager. WebLayoutManagerEx  run properly and I can change the gaps between items and captions. But I still need to override CreateLayoutManagerCore. Without overriding, the application is error "Constructor does not exist". Stack trace:
   at Fasterflect.Emitter.LookupUtils.GetConstructor(CallInfo callInfo)
   at Fasterflect.Emitter.CtorInvocationEmitter.CreateDelegate()
   at Fasterflect.Emitter.BaseEmitter.GetDelegate()
   at Fasterflect.ConstructorExtensions.DelegateForCreateInstance(Type type, Flags bindingFlags, Type[] parameterTypes)
   at Fasterflect.ConstructorExtensions.DelegateForCreateInstance(Type type, Type[] parameterTypes)
   at Fasterflect.ConstructorExtensions.CreateInstance(Type type, Object[] parameters)
   at Xpand.Persistent.Base.General.ViewExtensions.get_LayoutManager()

**Comment by apobekiaris** [comment]
the exception is pretty clear, you need a parameterless ctor in you WebLayoutManagerEx

**Comment by garung10a** [comment]
Exactly. Tks @apobekiaris
