### ISSUE TITLE
ExcelImporter doesn't propose property names

### ISSUE THREAD

**Issue by simonlary** [expand/eXpand#131]
In the screenshots in the Readme, the column mapping of the ExcelImporter has a dropdown menu to choose the business object's property from, but right now you have to enter the string manually. I found that the PopulatePropertyNamesController that does this is all commented out in that module. Is there any reason why it is commented out right now? I tried copying the controller in my project and it looks like it is working, but I guess there is a reason why it is disabled?

**Comment by apobekiaris** [comment]
not the PopulateController is not used, and I cannot tell without a sample why this happens. It works fine in both the ExcelImporterTester solution and the New Project Wizard

**Comment by simonlary** [comment]
I just created [this project](https://github.com/expand/eXpand/files/2258429/TestImport.zip), added the ExcelImporter NuGet packages and when I try to import [this excel file](https://github.com/expand/eXpand/files/2258426/Import.xlsx) I don't have any dropdown menu that appears.

**Comment by apobekiaris** [comment]
I am not sure how you make it map in the first place cause in your sample you missed to register the win Excel module, you need this call in the ctor of your windows module.

```cs
RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.Win.ExcelImporterWinModule));
```
after this I managed to map without problems.

**Comment by simonlary** [comment]
Well I was just being dumb there. I just forgot to add the platform-specific modules. Sorry about that, but thanks a lot for the help!
